#!/usr/bin/env ruby
#   Copyright 2009, David Martinez
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Change this key and run jiratothings -C to clear the login
CRYPT_KEY="djkhsfoiu345jknrjvxy87345jlhk3bnmkvcxljhulhHENPJdT"
# Change the filter id here. TODO Use by name and save it on the config.
JIRA_TASK_RE=/(.*-[0-9]*):(.*)/
JIRA_STATI_FOR_COMPLETED=["Resolved", "Closed"] # The status a completed JIRA project should have on your machine.
JIRA_QUERY = "assignee = currentUser() order by priority desc"
DEFAULT_PROJECT="Wurl"

require 'rubygems'
require 'getopt/long'
require 'yaml'
require 'jira'
require 'json'
require File.join(File.dirname(__FILE__), 'lib/simple_password_store')

require 'byebug' ; Debugger.start if defined? Debugger

def usage
  puts "Usage: jiratothings [--clear-login|-c]"
end

def main ()
  # Parse command line arguments
  begin
    opt = Getopt::Long.getopts ["--clear-login", "-C", Getopt::BOOLEAN]
  rescue
    usage()
    exit
  end

  # If -C or --clear-login passed, clear login info from stored password file
  if opt["clear-login"]
    begin
      File.unlink SimplePasswordStore::DEFAULT_PASSWORD_STORE
      puts "Cleared login from #{SimplePasswordStore::DEFAULT_PASSWORD_STORE}"
    rescue => e
      puts "Clearing login info from #{SimplePasswordStore::DEFAULT_PASSWORD_STORE} FAILED:"
      raise
    end
  end

  # Connect to OmniFocus and Jira
  password_store = SimplePasswordStore.new(consumer_key: true)
  jira_client = JIRA::Client.new({
                :username => password_store.username,
                :password => password_store.password,
                :site     => password_store.jira_url,
                :context_path => '',
                :auth_type => :basic
  })

  # Get issues from saved filter
  puts JIRA_QUERY
  report_results = jira_client.Issue.jql(JIRA_QUERY)

  # Only store the password when login went ok
  password_store.store_password unless ! password_store.store
  
  if report_results.nil? || report_results.length == 0
    puts "No results from JIRA report"
    exit
  end

  output = {
    :results=>[],
    :completed_stati => JIRA_STATI_FOR_COMPLETED,
    :default_project => DEFAULT_PROJECT
  }

  # Iterate through resulting issues.
  report_results.each do |row|
    jira_id = row.key
    title   = row.summary
    description = row.description
    task_name = "#{jira_id}: #{title}"
    task_notes = "#{password_store.jira_url}/browse/#{jira_id}\n#{description}"
    
    priority = row.priority
    priority_value = priority.nil? ? 99 : priority.id.to_i
    flagged = priority_value <= 3 ? true : false
    status = row.status.name
    output[:results] << {
      :task_name =>  task_name,
      :task_notes => task_notes,
      :status =>     status,
      :task_flagged => flagged
    }

    # TODO This goes to the JXA section
    # if ! things_client.has_jira?(jira_id)
    #   # Issue doesn't exist in OmniFocus.  let's add it.
    #   if ! JIRA_STATI_FOR_COMPLETED.include?(row['status'])
    #     puts "Adding #{task_name}"
    #     properties = {
    #       :task_name => task_name,
    #       :task_notes => task_notes,
    #       :task_flagged => (row['priority'].to_i <= 3 ? true : false)
    #     }
    #     things_client.add_task(properties)
    #   end
    # else
    #   # Issue does exist.  Should we mark it complete?
    #   if JIRA_STATI_FOR_COMPLETED.include?(row.status)
    #     things_client.mark_done(jira_id)
    #   else
    #     things_client.mark_undone(jira_id)
    #   end
    # end
    
  end # report_results.each

  # puts "\nWriting to temp file"
  file = Tempfile.new("jira-tasks")
  file.write(JSON.generate(output))
  file.close

  begin
    puts "\nRunning a bit of JXA AppleScript.."
    things_jxa = File.join(File.dirname(__FILE__), "lib/add_to_things.jxa")
    
    output = `#{things_jxa} #{file.path}`
    output.split("\n").each do |line|
      puts "[parent] output: #{line}"
    end
  rescue => e
    puts "Error - #{e.message}"
  end
  
  file.unlink
  
  
end

main if $0 == __FILE__
