#!/usr/bin/env ruby
#   Copyright 2009, David Martinez
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Which backend to use (Things in this case)
JXA_FILE = "add_to_omnifocus.jxa"
require File.join(File.dirname(__FILE__), 'lib/jira_to_jxa_app')

CONFIG_STORE_OPTIONS = {
  :config_store => "#{ENV['HOME']}/.jiratotaskmanagers/jira_to_omnifocus.yml",
  :task_app_params => [
    ConfigStore::Param.new("app_name", "Omnifocus App Name", "Omnifocus"),
    ConfigStore::Param.new("project_name", "Project Name:", "Work"),
    ConfigStore::Param.new("context", "Context:", "Office")
  ]
}
JiraToJxaApp.new.main if $0 == __FILE__
